FROM    centos:6.7
MAINTAINER      yur "wangzy509@chinaunicom.cn"


RUN     /bin/echo 'root:Qwe456123' |chpasswd
RUN     useradd five3
RUN     /bin/echo 'five3:123456' |chpasswd
RUN     /bin/echo -e "LANG=\"en_US.UTF-8\"" >/etc/default/local
EXPOSE  22
EXPOSE  80
EXPOSE  5000
CMD     /usr/sbin/sshd -D
